---
name: Python Tests
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python with a specific version
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.1
      - name: Test with pytest
        run: |
          pytest -vv
